[package]
name = "rlcc"
version = "0.1.0"
authors = ["jay"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1.37"
tracing-subscriber = "0.3.16"

[dev-dependencies]
test-generator = "0.3.1"
